<?php
    $_productCollection = $this->getCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!count($_productCollection)): ?>

<?php else: ?>
<div class="block">
	<div class="block-title"><strong><span><?php echo $this->__('Today deal'); ?></span></strong></div>
	<div class="block-content">
		<?php echo $this->getPagerHtml(); ?>
		<?php $_iterator = 0; ?>
		<ol class="products-list" >
		<?php foreach ($_productCollection as $_product): 
		
		?>
			<li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
				<?php // Product Image ?>
				<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>"  alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
				<?php // Product description ?>
				<div class="dealsidebar">
					<div class="f-fix">
						<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
						<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
						<!--
						<span>Sold: <?php echo (int)$_product->getSold(); ?></span>
						-->
						<div class="time-left-title" ><?php echo $this->__('Time Left:'); ?></div>
						<div class="time-left">
							<?php  $differenceInSeconds = strtotime($_product->getClosetime()) - time(); ?>
							<span class="clocktimer" value="<?php echo $differenceInSeconds ?>"></span>
						</div>
						<?php echo $this->getPriceHtml($_product, true); ?>
						<?php if($_product->isSaleable()): ?>
							<p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
						<?php else: ?>
							<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
						<?php endif; ?>
					</div>
				</div>
			</li>
		<?php endforeach; ?>
		</ol>
		<script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
	<div class="toolbar-bottom">
			<?php echo $this->getPagerHtml() ?>
		</div>
	</div>
</div>
<?php endif; ?>
