<br />
<div class="rmaForm hide-me" style="display: block;">
	<span style="color: #ff0000;"><strong>Our warranty is strictly 6 months from date of INVOICE unless specific to order. Batteries and consumables are only covered from 30 days from invoice date.</strong></span><p></p>
	<p>Once your RMA has been processed and you have received your RMA number, you will be required to return the goods back to us <strong>within 5 working days of the date issued</strong>. In the event that a replacement is unavailable, a refund will be issued. <strong>An RMA will not be processed without a completed form. All sections must be completed to obtain an RMA number</strong></p>
	<p><span style="color: #ff0000;"><strong>A 30% restocking fee will apply if ADD has accepted restock, for the following if applicable:</strong></span></p>
	<ul style="list-style: disc; padding-left: 30px; padding-bottom: 10px;">
		<li>Goods that customers have ordered incorrectly, or orders cancelled by the customer</li>
		<li>Non faulty goods that are not returned in their original condition (ie Retail Boxed now open)</li>
		<li>Goods returned as faulty and after testing have found to be working, but are no longer required by customer</li>
	</ul>
	<p>&nbsp;<br></p>
	<div lang="en-US" dir="ltr" id="wpcf7-f110-p108-o2" class="wpcf7">
		<div class="screen-reader-response"></div>
		<form novalidate="novalidate" enctype="multipart/form-data" class="wpcf7-form" method="post" action="/rma/#wpcf7-f110-p108-o2" name="">
			<div style="display: none;">
				<input type="hidden" value="110" name="_wpcf7">
				<input type="hidden" value="4.0.1" name="_wpcf7_version">
				<input type="hidden" value="en_US" name="_wpcf7_locale">
				<input type="hidden" value="wpcf7-f110-p108-o2" name="_wpcf7_unit_tag">
				<input type="hidden" value="fd6a90993f" name="_wpnonce">
			</div>
			<div class="form-list">
				<div class="row">
					<div class="col-sm-6">
						<div class="field">
		                    <label>Company Name*</label>
		                    <div class="input-box">
		                        <input type="text" class="input-text form-control" title="Company" value="" size="40" name="company_name">
		                    </div>
		                </div>
						<div class="field">
		                    <label>Contact Name*</label>
		                    <div class="input-box">
		                        <input type="text" class="input-text form-control" title="Company" value="" size="40" name="contact_name">
		                    </div>
		                </div>
						<div class="field">
		                    <label>Contact Telephone Number*</label>
		                    <div class="input-box">
		                        <input type="text" class="input-text form-control" title="Company" value="" size="40" name="contact_phone">
		                    </div>
		                </div>
						<div class="field">
		                    <label>Contact Email*</label>
		                    <div class="input-box">
		                        <input type="text" class="input-text form-control" title="Company" value="" size="40" name="contact_email">
		                    </div>
		                </div>
		            </div>
		            <div class="col-sm-6">
						<div class="field">
		                    <label>Customer Purchase Order Reference Number*</label>
		                    <div class="input-box">
		                        <input type="text" class="input-text form-control" title="Company" value="" size="40" name="ref_no">
		                    </div>
		                </div>
						<div class="field">
		                    <label>Invoice Number</label>
		                    <div class="input-box">
		                        <input type="text" class="input-text form-control" title="Company" value="" size="40" name="invoice_no">
		                    </div>
		                </div>
						<div class="field">
		                    <label>Date RMA Raised*</label>
		                    <div class="input-box">
		                        <input type="text" id="dateRMA" placeholder="dd/mm/yyyy" class="input-text form-control" title="Company" value="" size="40" name="date_rma">
		                    </div>
		                </div>
						<div class="field">
		                    <label>Date of Purchase*</label>
		                    <div class="input-box">
		                        <input type="text" id="datePurchase" placeholder="dd/mm/yyyy" class="input-text form-control" title="Company" value="" size="40" name="date_purchase">
		                    </div>
		                </div>
		            </div>
	            </div>
                <br />
				<div class="row product-1">
					<p class="rmaProduct">Product #1</p>
					<div class="col-sm-6">
						<div class="field">
		                    <label>Part Number*</label>
		                    <div class="input-box">
		                        <input type="text" class="input-text form-control" value="" size="40" name="part_number[]">
		                    </div>
		                </div>
						<div class="field">
		                    <label>Quantity*</label>
		                    <div class="input-box">
		                        <input type="text" class="input-text form-control" value="" size="40" name="quantity[]">
		                    </div>
		                </div>
						<div class="field">
		                    <label>Serial Number</label>
		                    <div class="input-box">
		                        <input type="text" class="input-text form-control" value="" size="40" name="serial_number[]">
		                    </div>
		                </div>
						<div class="field">
		                    <label>Warranty Sticker Number</label>
		                    <div class="input-box">
		                        <input type="text" class="input-text form-control" value="" size="40" name="warranty_sticker[]">
		                    </div>
		                </div>
	                </div>
					<div class="col-sm-6">
						<div class="field">
		                    <label>Reason for RMA* <br />(Please give as much information as possible)</label>
		                    <div class="input-box">
		                        <textarea class="input-text form-control" name="reason[]"></textarea>
		                    </div>
		                </div>
						<div class="field">
							<label for="exampleInputFile">Upload Image</label>
							<div style="clear:both;"><input type="file" name="upload_img[]" id="exampleInputFile"></div>
						</div>
		            </div>
				</div>
                <br />
				<div class="row product-2">
					<p class="rmaProduct">Product #2</p>
					<div class="col-sm-6">
						<div class="field">
		                    <label>Part Number*</label>
		                    <div class="input-box">
		                        <input type="text" class="input-text form-control" value="" size="40" name="part_number[]">
		                    </div>
		                </div>
						<div class="field">
		                    <label>Quantity*</label>
		                    <div class="input-box">
		                        <input type="text" class="input-text form-control" value="" size="40" name="quantity[]">
		                    </div>
		                </div>
						<div class="field">
		                    <label>Serial Number</label>
		                    <div class="input-box">
		                        <input type="text" class="input-text form-control" value="" size="40" name="serial_number[]">
		                    </div>
		                </div>
						<div class="field">
		                    <label>Warranty Sticker Number</label>
		                    <div class="input-box">
		                        <input type="text" class="input-text form-control" value="" size="40" name="warranty_sticker[]">
		                    </div>
		                </div>
	                </div>
					<div class="col-sm-6">
						<div class="field">
		                    <label>Reason for RMA* <br />(Please give as much information as possible)</label>
		                    <div class="input-box">
		                        <textarea class="input-text form-control" name="reason[]"></textarea>
		                    </div>
		                </div>
						<div class="field">
							<label for="exampleInputFile">Upload Image</label>
							<div style="clear:both;"><input type="file" name="upload_img[]" id="exampleInputFile"></div>
						</div>
		            </div>
				</div>
                <br />
				<div class="row product-3">
					<p class="rmaProduct">Product #3</p>
					<div class="col-sm-6">
						<div class="field">
		                    <label>Part Number*</label>
		                    <div class="input-box">
		                        <input type="text" class="input-text form-control" value="" size="40" name="part_number[]">
		                    </div>
		                </div>
						<div class="field">
		                    <label>Quantity*</label>
		                    <div class="input-box">
		                        <input type="text" class="input-text form-control" value="" size="40" name="quantity[]">
		                    </div>
		                </div>
						<div class="field">
		                    <label>Serial Number</label>
		                    <div class="input-box">
		                        <input type="text" class="input-text form-control" value="" size="40" name="serial_number[]">
		                    </div>
		                </div>
						<div class="field">
		                    <label>Warranty Sticker Number</label>
		                    <div class="input-box">
		                        <input type="text" class="input-text form-control" value="" size="40" name="warranty_sticker[]">
		                    </div>
		                </div>
	                </div>
					<div class="col-sm-6">
						<div class="field">
		                    <label>Reason for RMA* <br />(Please give as much information as possible)</label>
		                    <div class="input-box">
		                        <textarea class="input-text form-control" name="reason[]"></textarea>
		                    </div>
		                </div>
						<div class="field">
							<label for="exampleInputFile">Upload Image</label>
							<div style="clear:both;"><input type="file" name="upload_img[]" id="exampleInputFile"></div>
						</div>
		            </div>
				</div>
                <br />
				<div class="row product-4">
					<p class="rmaProduct">Product #4</p>
					<div class="col-sm-6">
						<div class="field">
		                    <label>Part Number*</label>
		                    <div class="input-box">
		                        <input type="text" class="input-text form-control" value="" size="40" name="part_number[]">
		                    </div>
		                </div>
						<div class="field">
		                    <label>Quantity*</label>
		                    <div class="input-box">
		                        <input type="text" class="input-text form-control" value="" size="40" name="quantity[]">
		                    </div>
		                </div>
						<div class="field">
		                    <label>Serial Number</label>
		                    <div class="input-box">
		                        <input type="text" class="input-text form-control" value="" size="40" name="serial_number[]">
		                    </div>
		                </div>
						<div class="field">
		                    <label>Warranty Sticker Number</label>
		                    <div class="input-box">
		                        <input type="text" class="input-text form-control" value="" size="40" name="warranty_sticker[]">
		                    </div>
		                </div>
	                </div>
					<div class="col-sm-6">
						<div class="field">
		                    <label>Reason for RMA* <br />(Please give as much information as possible)</label>
		                    <div class="input-box">
		                        <textarea class="input-text form-control" name="reason[]"></textarea>
		                    </div>
		                </div>
						<div class="field">
							<label for="exampleInputFile">Upload Image</label>
							<div style="clear:both;"><input type="file" name="upload_img[]" id="exampleInputFile"></div>
						</div>
		            </div>
				</div>
                <br />
				<div class="row product-5">
					<p class="rmaProduct">Product #5</p>
					<div class="col-sm-6">
						<div class="field">
		                    <label>Part Number*</label>
		                    <div class="input-box">
		                        <input type="text" class="input-text form-control" value="" size="40" name="part_number[]">
		                    </div>
		                </div>
						<div class="field">
		                    <label>Quantity*</label>
		                    <div class="input-box">
		                        <input type="text" class="input-text form-control" value="" size="40" name="quantity[]">
		                    </div>
		                </div>
						<div class="field">
		                    <label>Serial Number</label>
		                    <div class="input-box">
		                        <input type="text" class="input-text form-control" value="" size="40" name="serial_number[]">
		                    </div>
		                </div>
						<div class="field">
		                    <label>Warranty Sticker Number</label>
		                    <div class="input-box">
		                        <input type="text" class="input-text form-control" value="" size="40" name="warranty_sticker[]">
		                    </div>
		                </div>
	                </div>
					<div class="col-sm-6">
						<div class="field">
		                    <label>Reason for RMA* <br />(Please give as much information as possible)</label>
		                    <div class="input-box">
		                        <textarea class="input-text form-control" name="reason[]"></textarea>
		                    </div>
		                </div>
						<div class="field">
							<label for="exampleInputFile">Upload Image</label>
							<div style="clear:both;"><input type="file" name="upload_img[]" id="exampleInputFile"></div>
						</div>
		            </div>
				</div>
                <br />
			</div>
			<div class="row">
				<div class="col-sm-6 text-left">
					<p class="switch-window" id="more-products">+ Add Product</p>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-6 text-right">
					<button class="button btn-proceed-checkout btn-checkout" type="button">
						<span>
							<span>Submit Form</span>
						</span>
					</button>				
				</div>
			</div>
			<div class="wpcf7-response-output wpcf7-display-none"></div> 
		</form>
	</div>
	<p></p>
</div>
<script>
    jQuery("#dateRMA").datepicker({altFormat: "yyyy-mm-dd", dateFormat: "dd/mm/yy"});
    jQuery("#datePurchase").datepicker({altFormat: "yyyy-mm-dd", dateFormat: "dd/mm/yy"});
</script>
