<?php
    $_product = Mage::registry('product');
    $_helper = Mage::helper('catalog/output'); 
	$qvCf = Mage::getStoreConfig('quickview');
	$buttonTitle = $this->__('Add to cart');
?>

	<input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
	<input type="hidden" name="related_product" id="related-products-field" value="" />

	<?php if($_product->isSaleable()): ?>
		<div class="add-to-cart">
			<?php if(!$_product->isGrouped()): ?>
			<label for="qty"><?php echo $this->__('Qty:') ?></label>
			<input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
			<?php endif; ?>
			<button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><?php echo $buttonTitle ?></span></button>
			<?php echo $this->getChildHtml('', true, true) ?>
		</div>
	<?php endif; ?>
	