<?php
    $_productCollection = $this->getCollection();
    $_helper = $this->helper('catalog/output');
	$_dealHelper = $this->helper('dailydeal');
	$limit = 130;
?>

<?php echo $this->getChildHtml('dailydealtop'); ?>

<h2><?php echo $this->__('Upcoming deals'); ?></h2>
<?php if(!count($_productCollection)): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>


<div class="category-products">
    <?php echo $this->getPagerHtml(); ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" >
    <?php foreach ($_productCollection as $_product): 
    
    ?>
        <li class="dailydeal_list_content item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>"  alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
			
            <div class="dailydeal_center_block">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name">
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
					
					<div class="desc std">
                        <?php echo $_dealHelper->cuttext((string)$_product->getShortDescription(), $limit ) ?>
						<div class="link-learn">
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
						</div>
                    </div>

					<div class="time-left-title" ><?php echo $this->__('Deal start at:'); ?></div>
                    <div class="time-left" >
					
						<?php $differenceInSeconds = strtotime($_product->getStarttime()) - time(); ?>
						<span class="clocktimerdeal"><?php echo $this->formatTime($_product->getStarttime(),Mage_Core_Model_Locale::FORMAT_TYPE_MEDIUM, true); ?></span>
		        	</div>

                </div>
            </div>
			
			<div class="dailydeal_right_block">
			      <?php echo $this->getPriceHtml($_product, true); ?>
					<div class="yousave-sold">
						<span><?php echo $this->__('You save'); ?>: <span><?php echo (int)$_product->getSave(); ?>%</span></span>
						<span><?php echo $this->__('Sold'); ?>: <span><?php echo (int)$_product->getSold(); ?></span>/<?php echo $_product->getQuantity();?></span>
					</div>
                    <?php if($_product->isSaleable()): ?>
                        <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                 <?php endif; ?>
					
				 <ul class="add-to-links">
					<?php if ($this->helper('wishlist')->isAllow()) : ?>
						<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
					<?php endif; ?>
					<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
						<li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
					<?php endif; ?>
				</ul>
			</div>
	   </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
<div class="toolbar-bottom">
        <?php echo $this->getPagerHtml() ?>
    </div>
</div>
<?php endif; ?>